[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "exam-proctoring"
version = "0.1.0"
description = "Novel Framework for Malpractice Detection During Online Exam"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "numpy",
    "pandas",
    "mediapipe",
    "opencv-python",
    "scikit-learn",
    "scipy",
    "ultralytics",
    "pyyaml"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
pythonpath = [
    "src"
]
